In [ ]:
!pip install pandas

In [1]:
#dataset
import numpy as np
import pandas as pd
data = np.random.randint(4,6,(4,4))
data = {
    'student' : ["vijay" ,"raj" ,"rani" ,"ravi" ,"ramesh"],
    
    'rank' : [1 ,2 ,3 ,5 ,6],
    
    'marks' : [98 ,96 ,94 ,85 ,80]
}
res = pd.DataFrame(data)
print("student records \t\n",res)



student records 	
   student  rank  marks
0   vijay     1     98
1     raj     2     96
2    rani     3     94
3    ravi     5     85
4  ramesh     6     80


In [ ]:
import pandas as pd
my_list = [12,23,45,45,58]
res = pd.DataFrame(my_list)
print(res)

In [2]:
import pandas as pd
number_eries = pd.DataFrame([11,22,33,44,55,66],index = ['a','b','c','d','e','f'])
print(number_eries[0])




a    11
b    22
c    33
d    44
e    55
f    66
Name: 0, dtype: int64


In [3]:
import numpy as np
sample_2D_array = np.random.randint(3,4,(2,3,4))
print(sample_2D_array)

[[[3 3 3 3]
  [3 3 3 3]
  [3 3 3 3]]

 [[3 3 3 3]
  [3 3 3 3]
  [3 3 3 3]]]


In [ ]:
import numpy as pd
sample_2D_array = pd.random.randint(4,86,(4,4))
print(sample_2D_array)

In [4]:
import pandas as pd
var = [["vijay" , 10,100] , ["Raju" , 50,900] , ["rani" , 100,1000]]
df = pd.DataFrame(var,columns = ['Name' , 'Age' , 'Marks' ] ,  index = [1,2,3])
df

Name  Age  Marks
1  vijay   10    100
2   Raju   50    900
3   rani  100   1000

In [5]:
import pandas as pd
series_dict = { 'first_series': ([10,20,30,40,50,60]),
                'second_series': ([70,80,90,100,110,120])}
res = pd.DataFrame(series_dict)
res

first_series  second_series
0            10             70
1            20             80
2            30             90
3            40            100
4            50            110
5            60            120

In [ ]:
import pandas as pd
series_dict = { 'first_series':pd.Series ([10,20,30,40,50,60]),
                'second_series':pd.Series ([70,80,90,100,110,120])}
res = pd.DataFrame(series_dict)
res

In [ ]:
import pandas as pd
list_dicts = [{'a' :1 , 'b' :2 , 'c' :3 }, {'d' :4 , 'e' :5 , 'f' : 6}]
df = pd.DataFrame(list_dicts)
df

In [ ]:
import numpy as np
import pandas as pd
our_array = np.random.randn(100,5)
res= pd.DataFrame(our_array , columns =['A' , 'B' , 'C' , 'D' , 'E' ])
print(res)
# print(res.head(2))
# print(res.tail(1))
#print(res.info())
print(res.columns)

In [8]:
import pandas as pd
s1 = pd.Series([1])
print(s1)
s2 = pd.Series([11,22,33,44,55,66])
print(s2)
df = pd.DataFrame(s1 + s2)
df

0    1
dtype: int64
0    11
1    22
2    33
3    44
4    55
5    66
dtype: int64


0
0  12.0
1   NaN
2   NaN
3   NaN
4   NaN
5   NaN

In [ ]:
import pandas as pd 
	
# Calling DataFrame constructor 
df = pd.DataFrame() 
print(df) 

# list of strings 
lst = ['Geeks', 'For', 'Geeks', 'is', 'portal', 'for', 'Geeks'] 
	
# Calling DataFrame constructor on list 
df = pd.DataFrame(lst) 
print(df)


In [ ]:
import pandas as pd
data = pd.Series([2,3,4,5,6,7])
df = pd.DataFrame(s1 , index = ["raj","rani","ravi","raghu","vijju","vijay"])
#df
data1 = pd.Series([11,22,33,44,55,66])
df1 = pd.DataFrame(s2 , index = ["raj","rani","ravi","raghu","vijju","vijay"])
#df1
#print(data,"\n\n" ,data1)
print(data / data1)

In [5]:
# importing pandas module 
import pandas as pd 

# making data frame 
data = pd.read_csv("https://media.geeksforgeeks.org/wp-content/uploads/nba.csv") 

# number of rows to return 
n = 3

# creating series 
series = data["Name"] 

# returning top n rows 
top = series.head(n = n) 

# display 
top 


URLError: <urlopen error [Errno 11001] getaddrinfo failed>

In [4]:
# importing pandas module 
import pandas as pd 

# making data frame 
data = pd.read_csv("https://media.geeksforgeeks.org/wp-content/uploads/nba.csv") 

# calling tail() method 
# storing in new variable 
data_bottom = data.count() 

# display 
data_bottom 


URLError: <urlopen error [Errno 11001] getaddrinfo failed>

In [ ]:
import pandas as pd

In [8]:
#inpur CSV file
d= pd.read_csv("C:\\Users\\hepsi\\OneDrive\\Desktop\\vijay\\Students.csv")
df =pd.DataFrame(d)
df.tail(10)

Name       Team  Number Position   Age Height  Weight  \
448  Gordon Hayward  Utah Jazz    20.0       SF  26.0    6-8   226.0   
449     Rodney Hood  Utah Jazz     5.0       SG  23.0    6-8   206.0   
450      Joe Ingles  Utah Jazz     2.0       SF  28.0    6-8   226.0   
451   Chris Johnson  Utah Jazz    23.0       SF  26.0    6-6   206.0   
452      Trey Lyles  Utah Jazz    41.0       PF  20.0   6-10   234.0   
453    Shelvin Mack  Utah Jazz     8.0       PG  26.0    6-3   203.0   
454       Raul Neto  Utah Jazz    25.0       PG  24.0    6-1   179.0   
455    Tibor Pleiss  Utah Jazz    21.0        C  26.0    7-3   256.0   
456     Jeff Withey  Utah Jazz    24.0        C  26.0    7-0   231.0   
457             NaN        NaN     NaN      NaN   NaN    NaN     NaN   

      College      Salary  
448    Butler  15409570.0  
449      Duke   1348440.0  
450       NaN   2050000.0  
451    Dayton    981348.0  
452  Kentucky   2239800.0  
453    Butler   2433333.0  
454       NaN    900000.0  
455       NaN   2900000.0  
456    Kansas    947276.0  
457       NaN         NaN

In [9]:
d.isna().sum()

Name         1
Team         1
Number       1
Position     1
Age          1
Height       1
Weight       1
College     85
Salary      12
dtype: int64

In [12]:
X = d.iloc(:,:2).Numbers

SyntaxError: invalid syntax (1628473119.py, line 1)

In [ ]:
import pandas as pd

left = pd.DataFrame({'key1':['k0','k1','k2','k3'],
                     'key2':['k0','k1','k1','k0'],
                     'A' :['A0','A1','A2','A3'],
                     'B' :['B0','B1','B2','B3']})

right = pd.DataFrame({'key1':['k0','k1','k2','k3'],
                     'key2':['k0','k1','k1','k0'],
                     'A' :['A0','A1','A2','A3'],
                     'B' :['B0','B1','B2','B3']})
print(left + right)

In [5]:
import pandas as pd
Employee = {
     'Emp_name': ["vijay","rani","srinu","govi"],
     'Emp_id' : [123,234,344,565] ,
     'Emp_qualification' : ["Bsc", "Msc", "Phd", "Mtech"],                          
     'Emp_address' : ['Vijayawada','Guntur','Nellore','vizag']
}
res = pd.DataFrame(Employee)
#print("Employee records \n\n", res)
print("Emplotee id is \n ", res.Emp_id)


Emplotee id is 
  0    123
1    234
2    344
3    565
Name: Emp_id, dtype: int64
